language: node_js
node_js:
  - "stable"

jobs:
  include:
    - stage: npm release
      node_js: "stable"
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: vs@lutov.net
        on:
          tags: true
